create or replace view dm_aps.inventory_snapshot_view as
select fact.inventory_key as fact_inventory_key,
       fact.date_key as fact_date_key,
       fact.location_key as fact_location_key,
       fact.item_key as fact_item_key,
       fact.storage_location as fact_storage_location,
       fact.batch_nr as fact_batch_nr,
       fact.dull_date_key as fact_dull_date_key,
       fact.receipt_doc as fact_receipt_doc,
       fact.receipt_seq as fact_receipt_seq,
       fact.receipt_unit as fact_receipt_unit,
       fact.receipt_qty as fact_receipt_qty,
       fact.dull_date as fact_dull_date,
       fact.source as fact_source,
       fact.type as fact_type,
       fact.onhand as fact_onhand,
       fact.available as fact_available,
       fact.mrp_available as fact_mrp_available,
       fact.category as fact_category,
       fact.subcategory as fact_subcategory,
       fact.description as fact_description,
       fact.unit as fact_unit,
       fact.unit_price as fact_unit_price,
       fact.onhand_value as fact_onhand_value,
       loc.h_location_hk loc_h_location_hk,
       loc.load_date loc_load_date,
       loc.record_source loc_record_source,
       loc.location_nr loc_location_nr,
       loc.load_end_date loc_load_end_date,
       loc.location_hash_diff loc_location_hash_diff,
       loc.lft loc_lft,
       loc.rght loc_rght,
       loc.lvl loc_lvl,
       loc.source loc_source,
       loc.lastmodified loc_lastmodified,
       loc.created_at loc_created_at,
       loc.updated_at loc_updated_at,
       loc.name loc_name,
       loc.area loc_area,
       loc.category loc_category,
       loc.subcategory loc_subcategory,
       loc.description loc_description,
       loc.available_id loc_available_id,
       loc.owner_id loc_owner_id,
       loc.company loc_company,
       loc.type loc_type,
       item.h_item_hk as item_h_item_hk,
       item.load_date as item_load_date,
       item.record_source as item_record_source,
       item.item_nr as item_item_nr,
       item.load_end_date as item_load_end_date,
       item.item_hash_diff as item_item_hash_diff,
       item.product_group as item_product_group,
       item.product_category as item_product_category,
       item.product_type as item_product_type,
       item.product_usage as item_product_usage,
       item.supplier as item_supplier,
       item.supplier_type as item_supplier_type,
       item.packaging_type as item_packaging_type,
       item.packaging_qty as item_packaging_qty,
       item.unit as item_unit,
       item.unit_price as item_unit_price,
       item.inner_pkg as item_inner_pkg,
       item.outter_package as item_outter_package,
       item.strategy as item_strategy,
       item.nr as item_nr,
       item.name as item_name,
       item.barcode as item_barcode,
       item.type as item_type,
       item.status as item_status,
       item.plan_strategy as item_plan_strategy,
       item.lock_type as item_lock_type,
       item.lock_expire_at as item_lock_expire_at,
       item.price_abc as item_price_abc,
       item.qty_abc as item_qty_abc,
       item.COST as item_COST,
       item.SOURCE as item_SOURCE,
       item.owner_id as item_owner_id,
       item.gross_weight as item_gross_weight,
       item.net_weight as item_net_weight,
       item.physical_unit as item_physical_unit,
       item.project_nr as item_project_nr,
       item.mpq as item_mpq,
       item.outer_package_num as item_outer_package_num,
       item.pallet_num as item_pallet_num,
       item.outer_package_gross_weight as item_outer_package_gross_weight,
       item.pallet_gross_weight as item_pallet_gross_weight,
       item.outer_package_volume as item_outer_package_volume,
       item.pallet_volume as item_pallet_volume,
       item.plan_list_date as item_plan_list_date,
       item.plan_delist_date as item_plan_delist_date,
       item.category as item_category,
       item.subcategory as item_subcategory,
       item.description as item_description,
       item.lastmodified as item_lastmodified,
       item.created_at as item_created_at,
       item.updated_at as item_updated_at,
       item.lym as item_lym

from dm_aps.fact_inventory_daily_snapshot fact
         inner join dim_location loc on loc.h_location_hk = fact.location_key
         inner join dim_item item on fact.item_key = item.h_item_hk
         inner join dim_date shapshotdate on fact.date_key = shapshotdate.date_key
